COMPONENT_DEFAULTS = {
    "aio15": {
        "width_mm": 31.3,
        "length_mm": 31.3,
        "stack_height_mm": 6.0,
        "mount_pitch_mm": 25.5,
        "screw_diameter_mm": 2.0,
        "mass_g": 7.2,
        "source": "user: HDZero AIO15 dimensions, M2 mounting pattern and mass",
        "parameter_sources": {
            "stack_height_mm": "PROVISIONAL: complete populated board envelope; measure actual stack",
        },
    },
    "camera": {
        "length_mm": 14.0,
        "width_mm": 16.0,
        "height_mm": 14.0,
        "tilt_deg": 20.0,
        "mass_g": 2.3,
        "source": "user: HDZero Lux dimensions and mass",
        "parameter_sources": {"tilt_deg": "design: adjustable initial camera tilt"},
    },
    "battery": {
        "length_mm": 63.0,
        "width_mm": 30.0,
        "height_mm": 11.0,
        "mass_g": 37.0,
        "source": "user: GNB5502S120A dimensions and mass",
        "mass_scope": "battery including leads and connectors; represented at battery center",
    },
    "motor": {
        "diameter_mm": 16.0,
        "height_mm": 12.0,
        "mount_pitch_mm": 9.0,
        "mount_layout": "square",
        "screw_diameter_mm": 2.0,
        "screw_clearance_mm": 2.2,
        "mass_g": 6.0,
        "source": "user: 9 x 9 mm square mounting pattern",
        "parameter_sources": {
            "diameter_mm": "PROVISIONAL: motor model not selected",
            "height_mm": "PROVISIONAL: motor model not selected",
            "mass_g": "PROVISIONAL: motor model not selected",
            "screw_diameter_mm": "PROVISIONAL: M2; verify selected motor",
            "screw_clearance_mm": "design: 0.2 mm diametral clearance for M2",
        },
    },
    "prop": {
        "diameter_mm": 65.0,
        "thickness_mm": 0.8,
        "mass_g": 0.7,
        "source": "user: 65 mm swept disk; intentionally larger than exact 2.5 inch (63.5 mm)",
        "parameter_sources": {
            "thickness_mm": "PROVISIONAL: swept disk thickness; excludes blade flex",
            "mass_g": "PROVISIONAL: prop model not selected; equivalent uniform disk inertia",
        },
    },
    "xt30": {
        "width_mm": 10.2,
        "length_mm": 12.4,
        "height_mm": 5.2,
        "mass_g": 0.0,
        "source": "https://images.100y.com.tw/pdf_file/AMASS-XT30U.pdf#page=2",
        "model": "AMASS XT30U-F bounding envelope",
        "mass_scope": "already_in_battery",
        "parameter_sources": {
            "mass_g": "battery mass includes leads and connectors; avoid double counting",
        },
    },
    "balancer": {
        "width_mm": 9.8,
        "length_mm": 7.5,
        "height_mm": 5.7,
        "pins": 3,
        "mass_g": 0.0,
        "source": "https://www.jst-mfg.com/product/pdf/eng/eXH.pdf#page=4",
        "model": "PROVISIONAL: JST XHP-3 housing envelope; verify actual GNB connector",
        "mass_scope": "already_in_battery",
        "parameter_sources": {
            "pins": "user: 3-pin balance connector",
            "mass_g": "battery mass includes leads and connectors; avoid double counting",
        },
    },
}
