FEA_CONFIG = {
    "material": {
        "name": "PA6-CF, preliminary isotropic dry XY surrogate",
        "young_modulus_mpa": 4430.0,
        "poisson_ratio": 0.30,
        "density_g_cm3": 1.09,
        "source": "https://store.bblcdn.eu/s8/default/a64af9edb0f64095ad18bc4ad4faf1ec/Bambu_PA6-CF_Technical_Data_Sheet-v2.pdf",
        "assumptions": [
            "Bambu PA6-CF TDS: XY Young modulus 4430 +/- 310 MPa, density 1.09 g/cm3.",
            "Poisson ratio 0.30 is an unmeasured modeling assumption.",
            "Isotropic full-density surrogate; real printed Z modulus is lower (2170 +/- 230 MPa).",
            "No moisture, voids, plasticity, fatigue, damage or strain-rate dependence.",
        ],
    },
    "settings": {
        "mesh_size_mm": 3.0,
        "mesh_min_size_mm": 0.5,
        "mesh_curvature_points": 12,
        "mesh_threads": 1,
        "element_order": 2,
        "num_modes": 6,
        "work_dir": "exports/fea",
        "solver_path": None,
        "mesh_timeout_s": 180.0,
        "solver_timeout_s": 180.0,
        "threads": 2,
        "minimum_elastic_frequency_hz": 0.1,
        "stiffness_load_case": "arm_tip",
    },
}
