TOPOLOGY_CONFIG = {
    "grid": {
        "origin_mm": [-68.0, -64.0, 0.0],
        "spacing_mm": [4.0, 4.0, 4.0],
        "shape": [34, 32, 8],
        "axis_order": "xyz",
        "order": "C",
    },
    "component_clearance_mm": 0.5,
    "prop_clearance_mm": 2.0,
    "motor_contact_radius_mm": 9.5,
    "aio_contact_radius_mm": 3.2,
    "contact_depth_mm": 4.0,
    "camera_contact_width_mm": 4.0,
    "camera_contact_length_mm": 8.0,
    "battery_contact_width_mm": 8.0,
    "battery_contact_length_mm": 8.0,
    "battery_contact_y_mm": 20.0,
    "connection_proof_force_n": 0.05,
    "manufacturing": {
        "nozzle_width_mm": 0.4,
        "minimum_wall_nozzles": 5.0,
        "minimum_feature_mm": 2.0,
        "minimum_attachment_area_mm2": 8.0,
        "supports_allowed": True,
        "build_direction": [0.0, 0.0, 1.0],
        "assumptions": [
            "External and accessible internal supports are allowed; not a support-free design.",
            "Coarse density cells do not resolve mounting bores; exact reconstruction cuts them.",
            "Nozzle width and track count are provisional manufacturing inputs.",
            "Feature and attachment checks are geometric screens, not print-process certification.",
        ],
    },
    "optimizer": {
        "interface_node_policy": "preserve_adjacent",
        "volume_fraction": 0.10,
        "filter_radius_mm": 6.0,
        "penalization": 3.0,
        "min_stiffness_ratio": 1e-6,
        "max_iterations": 45,
        "change_tolerance": 0.015,
        "move_limit": 0.12,
        "projection_beta": 1.0,
    },
    "reconstruction": {
        "density_threshold": 0.35,
        "minimum_feature_mm": 2.0,
    },
    "additional_regions": [],
}
